"""Company Registry for NL-45 (Grievance Disposal)."""

COMPANY_MAP = {
    "care": "care_health",
    "star": "star_health",
    "bajaj allianz": "bajaj_allianz",
    "bajaj": "bajaj_allianz",
    "bajajgeneral": "bajaj_allianz",
    "bgil": "bajaj_allianz",
    "hdfc ergo": "hdfc_ergo",
    "hdfcergo": "hdfc_ergo",
    "national insurance": "national_insurance",
    "nationalinsurance": "national_insurance",
    "nic": "national_insurance",
    "new india": "new_india",
    "newindia": "new_india",
    "oriental insurance": "oriental_insurance",
    "orientalinsurance": "oriental_insurance",
    "united india": "united_india",
    "unitedindia": "united_india",
    "godigit": "go_digit",
    "go digit": "go_digit",
    "digit general": "go_digit",
    "cholamandalam": "chola_ms",
    "chola ms": "chola_ms",
    "chola general": "chola_ms",
    "chola": "chola_ms",
    "icici lombard": "icici_lombard",
    "icici lombard general": "icici_lombard",
    "icici": "icici_lombard",
    "acko": "acko",
    "tata aig": "tata_aig",
    "reliance general": "indusind_general",
    "reliance": "indusind_general",
    "royal sundaram": "royal_sundaram",
    "future generali": "future_generali",
    "futuregenerali": "future_generali",
    "generali central": "future_generali",
    "generalicentral":"future_generali",
    "generali":"future_generali",
    "shriram general": "shriram_general",
    "shriram": "shriram_general",
    "zurich kotak": "zurich_kotak",
    "kotak mahindra general": "zurich_kotak",
    "kotak": "zurich_kotak",
    "zuno": "zuno",
    "edelweiss general": "zuno",
    "agriculture insurance company": "aic",
    "agriculture insurance company of india": "aic",
    "aicof": "aic",
    "aic": "aic",
    "ecgc limited": "ecgc",
    "navi general": "navi_general",
    "navi": "navi_general",
    "raheja qbe": "raheja_qbe",
    "raheja": "raheja_qbe",
    "universal sompo": "universal_sompo",
    "universalsompo": "universal_sompo",
    "iffco tokio": "iffco_tokio",
    "iffco-tokio": "iffco_tokio",
    "iffco": "iffco_tokio",
    "liberty": "liberty_general",
    "liberty general": "liberty_general",
    "magma general": "magma_general",
    "magma hdi": "magma_general",
    "magma": "magma_general",
    "niva bupa": "niva_bupa",
    "nivabupa": "niva_bupa",
    "aditya birla": "aditya_birla_health",
    "adityabirla": "aditya_birla_health",
    "narayana health": "narayana_health",
    "narayanahealth": "narayana_health",
    "narayana": "narayana_health",
    "manipal cigna": "manipal_cigna",
    "manipalcigna": "manipal_cigna",
    "manipal": "manipal_cigna",
    "care health": "care_health",
    "carehealth": "care_health",
    "galaxy health": "galaxy_health",
    "galaxyhealth": "galaxy_health",
    "ecgc": "ecgc",
    "sbi": "sbi_general",
    "sbi general": "sbi_general",
    "kshema": "kshema_general",
    "kshema general": "kshema_general",
    "indusind": "indusind_general",
    "indusind general": "indusind_general",
}

COMPANY_DISPLAY_NAMES = {
    "bajaj_allianz":     "Bajaj Allianz General Insurance",
    "hdfc_ergo":         "HDFC ERGO General Insurance",
    "national_insurance":"National Insurance Company",
    "new_india":         "The New India Assurance Company",
    "oriental_insurance":"The Oriental Insurance Company",
    "united_india":      "United India Insurance Company",
    "go_digit":          "Go Digit General Insurance Limited",
    "chola_ms":          "Cholamandalam MS General Insurance Company Limited",
    "icici_lombard":     "ICICI Lombard General Insurance Company Limited",
    "acko":              "ACKO General Insurance Limited",
    "tata_aig":          "Tata AIG General Insurance Company Limited",
    "royal_sundaram":    "Royal Sundaram General Insurance Co. Limited",
    "future_generali":   "Future Generali India Insurance Company Limited",
    "sbi_general":       "SBI General Insurance Company Limited",
    "shriram_general":   "Shriram General Insurance Company Limited",
    "zurich_kotak":      "Zurich Kotak General Insurance Company (India) Limited",
    "zuno":              "ZUNO General Insurance Limited",
    "aic":               "Agriculture Insurance Company of India Limited",
    "navi_general":      "Navi General Insurance Limited",
    "raheja_qbe":        "Raheja QBE General Insurance Company Limited",
    "universal_sompo":   "Universal Sompo General Insurance Company Limited",
    "iffco_tokio":       "IFFCO Tokio General Insurance Company Limited",
    "liberty_general":   "Liberty General Insurance Company Limited",
    "magma_general":       "Magma General Insurance Limited",
    "kshema_general":      "Kshema General Insurance Limited",
    "indusind_general":    "IndusInd General Insurance Company Limited",
    "niva_bupa":           "Niva Bupa Health Insurance Company Limited",
    "aditya_birla_health": "Aditya Birla Health Insurance Co. Limited",
    "generali_central":    "Generali Central Insurance Co. Limited",
    "narayana_health":     "Narayana Health Insurance Limited",
    "manipal_cigna":       "Manipal Cigna Health Insurance Company Limited",
    "care_health":         "Care Health Insurance Limited",
    "galaxy_health":       "Galaxy Health Insurance Company Limited",
    "ecgc":                "ECGC Limited",
}

DEDICATED_PARSER: dict = {
    "new_india":           "parse_new_india",
    "aditya_birla_health": "parse_aditya_birla",
}
